# -*- coding: utf-8 -*-
"""Sistem Otomatisasi Rekapitulasi Keluhan Masyarakat .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6YiaevmMrKBjowmp_A_GiXAv9WHQh3v
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

excel_url = 'https://drive.google.com/uc?id=1R2QexUC96e7X6NJfhcuJNLa_zMay1snF&export=download'
data=pd.read_excel(excel_url)
data

data_rkm=data[['Instansi','Topik','Channel','Status']]
data_rkm

data.info()

data.Status.value_counts()

# hanya Status yang selesai
data_selesai=data[data['Status']=='Selesai']
data_selesai

data_selesai.info()

# membuat dataframe kosong
rkm=pd.DataFrame()
rkm

# isi dataframe dengan instansi yang unik dari data selesai
rkm['Instansi']=data_selesai.Instansi.unique()
rkm

# mengambil Topik yang unik pada setiap Instansi
rkm['Topik'] = rkm['Instansi'].apply(
    lambda x: list(set(data_selesai[data_selesai['Instansi'] == x]['Topik']))
)
rkm

# Jumlah keluhan
rkm['Jumlah'] = rkm['Instansi'].apply(
    lambda x: data_selesai[data_selesai['Instansi'] == x]['Status'].count()
)
rkm

# Jumlah Ditindaklanjuti
rkm['Ditindaklanjuti'] = rkm['Instansi'].apply(
    lambda x: data_selesai[data_selesai['Instansi'] == x]['Status'].count()
)
rkm

# Belum ditindaklanjuti
rkm['Belum Ditindaklanjuti'] = rkm['Jumlah'] - rkm['Ditindaklanjuti']
rkm

# atur ulang data frame
rkm=rkm[['Instansi','Jumlah','Ditindaklanjuti','Belum Ditindaklanjuti','Topik']]
rkm

# urutkan dataframe dari jumlah terbanyak
rkm=rkm.sort_values(by='Jumlah',ascending=False).reset_index(drop=True)
rkm

katagori_keluhan = pd.DataFrame()
katagori_keluhan = data_selesai['Channel'].value_counts().reset_index()
katagori_keluhan.columns = ['Channel', 'Jumlah']

katagori_keluhan